name: Docker build CI


on:
    workflow_dispatch:
        inputs:
          image_name:
            description: 'naming the image'
            required: true
            default: 'web-water'
            type: string
          tag:
            description: "image tag"
            required: true
            type: string
         
env:
    IMAGE_NAME: ${{ inputs.image_name }}
    TAG: ${{ inputs.tag }}
    

jobs:
    build_image:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v4


            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: docker build and push
              run: |
                   docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG .
                   docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$TAG

                   


            